theme: jekyll-theme-architect
title: Market Analysis
description: Getting thoughts on paper

<img src="https://taz-ali.github.io/docs/images/RecessionsSP500.png" style="display: block; margin: auto;" />
